/*
 * @author Mário Soares
 * @contributors Jefferson González
 * @contributors René Vögeli / Rangee GmbH
 * 
 * @license 
 * This file is part of wxPHP check the LICENSE file for information.
 * 
 * @note
 * This file was auto-generated by the wxPHP source maker
*/

#ifndef WXPHP_DOCVIEW_H_GUARD
#define WXPHP_DOCVIEW_H_GUARD

#include "references.h"
#include "object_types.h"

ZEND_BEGIN_ARG_INFO_EX(wxphp_docview_get_args, 0, 0, 1)
    ZEND_ARG_INFO(0, name)
ZEND_END_ARG_INFO()

extern zend_class_entry* php_wxView_entry;
extern zend_object_handlers wxphp_wxView_object_handlers;
void php_wxView_destruction_handler(zend_resource*);

class wxView_php: public wxView{
    public:

    wxView_php():wxView(){}
    
    void OnActivateView(bool activate, wxView* activeView, wxView* deactiveView);
    void OnChangeFilename();
    bool OnClose(bool deleteWindow);
    void OnClosingDocument();
    wxPrintout* OnCreatePrintout();
    void OnDraw(wxDC* dc);
    void OnUpdate(wxView* sender, wxObject* hint=0);
    
    void InitProperties(){
        properties = new void*[3];

        properties[0] = &m_viewDocument;
        properties[1] = &m_viewFrame;
        properties[2] = &m_viewTypeName;
        
    }

    void UninitProperties(){
        delete[] properties;
    }

    void** properties;

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxView{
    wxView_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxView;

void php_wxView_free(void *object);
zend_object* php_wxView_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
ZEND_BEGIN_ARG_INFO_EX(php_wxView___construct_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, other)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_Activate_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, activate)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_Close_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, deleteWindow)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_GetFrame_arg_infos, 0, 0, 0)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_GetViewName_arg_infos, 0, 0, 0)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_SetFrame_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, frame)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_SetViewName_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, name)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_Connect_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, id)
    ZEND_ARG_INFO(0, lastId)
    ZEND_ARG_INFO(0, eventType)
    ZEND_ARG_INFO(0, function)
    ZEND_ARG_INFO(0, userData)
    ZEND_ARG_INFO(0, eventSink)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_Disconnect_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, id)
    ZEND_ARG_INFO(0, lastId)
    ZEND_ARG_INFO(0, eventType)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_AddFilter_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, filter)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_AddPendingEvent_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, event)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_DeletePendingEvents_arg_infos, 0, 0, 0)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_GetEvtHandlerEnabled_arg_infos, 0, 0, 0)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_GetNextHandler_arg_infos, 0, 0, 0)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_GetPreviousHandler_arg_infos, 0, 0, 0)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_IsUnlinked_arg_infos, 0, 0, 0)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_ProcessEvent_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, event)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_ProcessEventLocally_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, event)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_ProcessPendingEvents_arg_infos, 0, 0, 0)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_QueueEvent_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, event)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_RemoveFilter_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, filter)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_SafelyProcessEvent_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, event)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_SetEvtHandlerEnabled_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, enabled)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_SetNextHandler_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, handler)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_SetPreviousHandler_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, handler)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_Unlink_arg_infos, 0, 0, 0)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_UnShare_arg_infos, 0, 0, 0)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_UnRef_arg_infos, 0, 0, 0)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_IsSameAs_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, obj)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_Ref_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, clone)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_GetClassInfo_arg_infos, 0, 0, 0)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxView_IsKindOf_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, info)
ZEND_END_ARG_INFO()

static zend_function_entry php_wxView_functions[] = {
    PHP_ME(php_wxView, __construct, php_wxView___construct_arg_infos, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_ME(php_wxView, Activate, php_wxView_Activate_arg_infos, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxView, Close, php_wxView_Close_arg_infos, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxView, GetFrame, php_wxView_GetFrame_arg_infos, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxView, GetViewName, php_wxView_GetViewName_arg_infos, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxView, SetFrame, php_wxView_SetFrame_arg_infos, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxView, SetViewName, php_wxView_SetViewName_arg_infos, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxView, __get, wxphp_docview_get_args, ZEND_ACC_PUBLIC)
    PHP_FE_END
};
#endif


static inline zo_wxView * php_wxView_fetch_object(zend_object *obj) {
    return (zo_wxView *)(
        (char *)(obj) - XtOffsetOf(zo_wxView, zo)
    );
}

#define Z_wxView_P(zv) \
    php_wxView_fetch_object(Z_OBJ_P(zv))
extern zend_class_entry* php_wxFileHistory_entry;
extern zend_object_handlers wxphp_wxFileHistory_object_handlers;
void php_wxFileHistory_destruction_handler(zend_resource*);

class wxFileHistory_php: public wxFileHistory{
    public:

    wxFileHistory_php(size_t maxFiles=9, wxWindowID idBase=wxID_FILE1):wxFileHistory(maxFiles, idBase){}
    
    

    zval phpObj;
    wxPHPObjectReferences references;
};

BEGIN_EXTERN_C()
typedef struct _zo_wxFileHistory{
    wxFileHistory_php* native_object;
    wxphp_object_type object_type;
    int is_user_initialized;
    zend_object zo;
} zo_wxFileHistory;

void php_wxFileHistory_free(void *object);
zend_object* php_wxFileHistory_new(zend_class_entry *class_type);
END_EXTERN_C()

#ifdef WXPHP_INCLUDE_METHOD_TABLES
ZEND_BEGIN_ARG_INFO_EX(php_wxFileHistory_AddFileToHistory_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, filename)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxFileHistory_AddFilesToMenu_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, menu)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxFileHistory_GetBaseId_arg_infos, 0, 0, 0)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxFileHistory_GetCount_arg_infos, 0, 0, 0)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxFileHistory_GetHistoryFile_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, index)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxFileHistory_GetMaxFiles_arg_infos, 0, 0, 0)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxFileHistory_Load_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, config)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxFileHistory_RemoveFileFromHistory_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, i)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxFileHistory_RemoveMenu_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, menu)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxFileHistory_Save_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, config)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxFileHistory_SetBaseId_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, baseId)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxFileHistory_UseMenu_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, menu)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxFileHistory___construct_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, maxFiles)
    ZEND_ARG_INFO(0, idBase)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxFileHistory_UnShare_arg_infos, 0, 0, 0)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxFileHistory_UnRef_arg_infos, 0, 0, 0)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxFileHistory_IsSameAs_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, obj)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxFileHistory_Ref_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, clone)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxFileHistory_GetClassInfo_arg_infos, 0, 0, 0)
ZEND_END_ARG_INFO()
ZEND_BEGIN_ARG_INFO_EX(php_wxFileHistory_IsKindOf_arg_infos, 0, 0, 0)
    ZEND_ARG_INFO(0, info)
ZEND_END_ARG_INFO()

static zend_function_entry php_wxFileHistory_functions[] = {
    PHP_ME(php_wxFileHistory, AddFileToHistory, php_wxFileHistory_AddFileToHistory_arg_infos, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxFileHistory, AddFilesToMenu, php_wxFileHistory_AddFilesToMenu_arg_infos, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxFileHistory, GetBaseId, php_wxFileHistory_GetBaseId_arg_infos, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxFileHistory, GetCount, php_wxFileHistory_GetCount_arg_infos, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxFileHistory, GetHistoryFile, php_wxFileHistory_GetHistoryFile_arg_infos, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxFileHistory, GetMaxFiles, php_wxFileHistory_GetMaxFiles_arg_infos, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxFileHistory, Load, php_wxFileHistory_Load_arg_infos, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxFileHistory, RemoveFileFromHistory, php_wxFileHistory_RemoveFileFromHistory_arg_infos, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxFileHistory, RemoveMenu, php_wxFileHistory_RemoveMenu_arg_infos, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxFileHistory, Save, php_wxFileHistory_Save_arg_infos, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxFileHistory, SetBaseId, php_wxFileHistory_SetBaseId_arg_infos, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxFileHistory, UseMenu, php_wxFileHistory_UseMenu_arg_infos, ZEND_ACC_PUBLIC)
    PHP_ME(php_wxFileHistory, __construct, php_wxFileHistory___construct_arg_infos, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
    PHP_FE_END
};
#endif


static inline zo_wxFileHistory * php_wxFileHistory_fetch_object(zend_object *obj) {
    return (zo_wxFileHistory *)(
        (char *)(obj) - XtOffsetOf(zo_wxFileHistory, zo)
    );
}

#define Z_wxFileHistory_P(zv) \
    php_wxFileHistory_fetch_object(Z_OBJ_P(zv))
#endif //WXPHP_DOCVIEW_H_GUARD
